### ISSUE TITLE
登录时baidu居然让我输入验证码真是丧心病狂

### ISSUE THREAD

**Issue by laolai** [yangyangwithgnu/yosong#1]
还提示出一个验证码的连接，浏览器直接打开是一个验证码的小图片，在命令行输入直接就报错，难道要我在VPS上先手动登录一把百度。。

**Comment by yangyangwithgnu** [comment]
首先你得确认你输入的帐号和密码无误（浏览器中登录百毒）；
其次你得确认是否安装 v0.1.1；
然后你得清楚只要不是频繁登录百度，不会出现验证码；
最后既然你在这儿反应问题，为何不把报错信息贴出来？
