### ISSUE TITLE
解析太快居然被认为是被 DDos 了

### ISSUE THREAD

**Issue by pupboss** [yangyangwithgnu/yosong#3]
![screen shot 2015-11-22 at 1 26 47 am](https://cloud.githubusercontent.com/assets/8395112/11319633/669d9f7c-90b8-11e5-8464-f6b350da2adf.png)

实时网速看了，大概是每秒 20~30 兆

**Comment by pupboss** [comment]
上面的图略慢 = =

![Screen Shot 2015-11-22 at 1.26.47 AM.png](https://ooo.0o0.ooo/2015/11/21/5650aae8ed985.png)

对了还有，User Agent 还得改成以前的，不然老是登录失败，验证码都不提示了

**Comment by yangyangwithgnu** [comment]
你反应的两个问题，一个是高频访问导致无法解析歌曲地址，一是 UA 设置导致无法登录。

第一个问题，的确是，我刚优化了下，升级到 v0.1.4 可以解决，yosong 中加了重试机制；

第二个问题，我测试的情况是，通过宽带接入，UA 必须为空才能登录，通过 4G 接入，UA 必须为移动终端才能登录。考虑到大部份同学用到宽带，所以，暂不调整了。

**Comment by pupboss** [comment]
好的 多谢！
